"""input

Revision ID: 03e3ff5c092d
Revises: 197a2916d137
Create Date: 2023-08-12 19:52:20.984615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03e3ff5c092d'
down_revision = '197a2916d137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_input2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('text_input3', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('text_input3')
        batch_op.drop_column('text_input2')

    # ### end Alembic commands ###
