"""new

Revision ID: 07676333bb56
Revises: 03e3ff5c092d
Create Date: 2023-08-12 20:12:27.283798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07676333bb56'
down_revision = '03e3ff5c092d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pics_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('text_input4', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('text_input5', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('text_input5')
        batch_op.drop_column('text_input4')
        batch_op.drop_column('pics_2')

    # ### end Alembic commands ###
