"""Initial migration.

Revision ID: 144f8bcffbc0
Revises: eb1ee9200f47
Create Date: 2023-07-30 16:10:06.440796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '144f8bcffbc0'
down_revision = 'eb1ee9200f47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('pinned_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinned_date', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
