"""header

Revision ID: 197a2916d137
Revises: b2df4626305c
Create Date: 2023-08-12 11:42:01.838386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '197a2916d137'
down_revision = 'b2df4626305c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_input1', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('text_input1')

    # ### end Alembic commands ###
