"""empty message

Revision ID: 2933f762b6cf
Revises: 96b64294876f
Create Date: 2023-08-25 12:06:34.338684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2933f762b6cf'
down_revision = '96b64294876f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('picx', sa.String(length=255), nullable=True))
        batch_op.drop_column('pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pic', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('picx')

    # ### end Alembic commands ###
