"""empty message

Revision ID: 96b64294876f
Revises: b31edf4b7335
Create Date: 2023-08-14 21:07:00.885573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96b64294876f'
down_revision = 'b31edf4b7335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pit', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pit_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pit_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pit_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pit_4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pit_5', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pit_6', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pit_7', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pit_8', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pit_9', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input3', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input4', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input5', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input6', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input7', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input8', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input9', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input10', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input11', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input12', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input13', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input14', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input15', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input16', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input17', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input18', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('tuxts_input19', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('tuxts_input19')
        batch_op.drop_column('tuxts_input18')
        batch_op.drop_column('tuxts_input17')
        batch_op.drop_column('tuxts_input16')
        batch_op.drop_column('tuxts_input15')
        batch_op.drop_column('tuxts_input14')
        batch_op.drop_column('tuxts_input13')
        batch_op.drop_column('tuxts_input12')
        batch_op.drop_column('tuxts_input11')
        batch_op.drop_column('tuxts_input10')
        batch_op.drop_column('tuxts_input9')
        batch_op.drop_column('tuxts_input8')
        batch_op.drop_column('tuxts_input7')
        batch_op.drop_column('tuxts_input6')
        batch_op.drop_column('tuxts_input5')
        batch_op.drop_column('tuxts_input4')
        batch_op.drop_column('tuxts_input3')
        batch_op.drop_column('tuxts_input2')
        batch_op.drop_column('tuxts_input1')
        batch_op.drop_column('tuxts_input')
        batch_op.drop_column('pit_9')
        batch_op.drop_column('pit_8')
        batch_op.drop_column('pit_7')
        batch_op.drop_column('pit_6')
        batch_op.drop_column('pit_5')
        batch_op.drop_column('pit_4')
        batch_op.drop_column('pit_3')
        batch_op.drop_column('pit_2')
        batch_op.drop_column('pit_1')
        batch_op.drop_column('pit')

    # ### end Alembic commands ###
