"""empty message

Revision ID: b2df4626305c
Revises: be38183c5870
Create Date: 2023-08-06 14:41:41.781919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2df4626305c'
down_revision = 'be38183c5870'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('text_input',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('text_input',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)

    # ### end Alembic commands ###
