"""empty message

Revision ID: b31edf4b7335
Revises: 38fff2f72bf0
Create Date: 2023-08-14 14:49:09.291473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b31edf4b7335'
down_revision = '38fff2f72bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('texts_input', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input1', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input3', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input4', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input5', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input6', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input7', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input8', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input9', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input10', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input11', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input12', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input13', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input14', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input15', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input16', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input17', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input18', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('texts_input19', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('pic', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_1', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_2', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_4', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_5', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_6', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_7', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_8', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pic_9', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('pic_9')
        batch_op.drop_column('pic_8')
        batch_op.drop_column('pic_7')
        batch_op.drop_column('pic_6')
        batch_op.drop_column('pic_5')
        batch_op.drop_column('pic_4')
        batch_op.drop_column('pic_3')
        batch_op.drop_column('pic_2')
        batch_op.drop_column('pic_1')
        batch_op.drop_column('pic')
        batch_op.drop_column('texts_input19')
        batch_op.drop_column('texts_input18')
        batch_op.drop_column('texts_input17')
        batch_op.drop_column('texts_input16')
        batch_op.drop_column('texts_input15')
        batch_op.drop_column('texts_input14')
        batch_op.drop_column('texts_input13')
        batch_op.drop_column('texts_input12')
        batch_op.drop_column('texts_input11')
        batch_op.drop_column('texts_input10')
        batch_op.drop_column('texts_input9')
        batch_op.drop_column('texts_input8')
        batch_op.drop_column('texts_input7')
        batch_op.drop_column('texts_input6')
        batch_op.drop_column('texts_input5')
        batch_op.drop_column('texts_input4')
        batch_op.drop_column('texts_input3')
        batch_op.drop_column('texts_input2')
        batch_op.drop_column('texts_input1')
        batch_op.drop_column('texts_input')

    # ### end Alembic commands ###
