"""empty message

Revision ID: d29e98ff365d
Revises: 07676333bb56
Create Date: 2023-08-13 21:24:13.281403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd29e98ff365d'
down_revision = '07676333bb56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pics_3', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pics_5', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('text_input6', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('text_input7', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('text_input8', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('text_input9', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('text_input10', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('text_input11', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('text_input11')
        batch_op.drop_column('text_input10')
        batch_op.drop_column('text_input9')
        batch_op.drop_column('text_input8')
        batch_op.drop_column('text_input7')
        batch_op.drop_column('text_input6')
        batch_op.drop_column('pics_5')
        batch_op.drop_column('pics_3')

    # ### end Alembic commands ###
