"""empty message

Revision ID: dd905f86bfce
Revises: 2933f762b6cf
Create Date: 2023-08-25 12:17:08.716458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd905f86bfce'
down_revision = '2933f762b6cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pitx', sa.String(length=255), nullable=True))
        batch_op.drop_column('pit')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pit', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('pitx')

    # ### end Alembic commands ###
